#MQTT配置
com:
  mqtt:
    url: tcp://huanan0001.mqtt.iot.gz.baidubce.com:1883
    clientId: ${random.value}
    topics: tp000415001,t190613006,t200416002,t200427002
    username: huanan0001/gslq
    password: 0piHQlo7Zr06HEqe
    timeout: 30
    keepalive: 60       #心跳60S

spring:
  #ActiveMQ配置
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    in-memory: false

  #Redis配置
  redis:
    database: 0          # Redis数据库索引（默认为0）
    host: 127.0.0.1
    port: 6379
    password:            # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8    # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8      # 连接池中的最大空闲连接
        max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0      # 连接池中的最小空闲连接

